//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JanHafner.Restify.Services.OAuth2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JanHafner.Restify.Services.OAuth2.Properties.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The context is already authorized..
        /// </summary>
        internal static string AlreadyAuthorizedExceptionMessage {
            get {
                return ResourceManager.GetString("AlreadyAuthorizedExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Bearer-Authorization header can not be created due the lack of authorization..
        /// </summary>
        internal static string CantCreateBearerDueTheLackOfAuthorizationExceptionMessage {
            get {
                return ResourceManager.GetString("CantCreateBearerDueTheLackOfAuthorizationExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization can not be refreshed due the lack of authorization..
        /// </summary>
        internal static string CantRefreshAuthorizationDueTheLackOfAuthorizationExceptionMessage {
            get {
                return ResourceManager.GetString("CantRefreshAuthorizationDueTheLackOfAuthorizationExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The access token can not be revoked due the lack of authorization..
        /// </summary>
        internal static string CantRevokeAuthorizationDueTheLackOfAuthorizationExceptionMessage {
            get {
                return ResourceManager.GetString("CantRevokeAuthorizationDueTheLackOfAuthorizationExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The authorization context needs grant on &apos;{0}&apos; for request &apos;{1}&apos;.
        /// </summary>
        internal static string InsufficientAuthorizationExceptionMessage {
            get {
                return ResourceManager.GetString("InsufficientAuthorizationExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request needs to be authorized but the authorization context has not handled the authorization process..
        /// </summary>
        internal static string RequestNeedsAuthorizationExceptionMessage {
            get {
                return ResourceManager.GetString("RequestNeedsAuthorizationExceptionMessage", resourceCulture);
            }
        }
    }
}
